# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Importaciones:**

In [ ]:
import numpy as np
from random import randint

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [ ]:
#todo: 
array = np.arange(10) # Usamos el metodo arange para crear un array de 10 elementos
print(array) # imprimimos el array



[0 1 2 3 4 5 6 7 8 9]


**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [5]:
#todo:
# Creamos un array de 5 elementos, todos inicializados en cero, usando el método zeros().
array = np.zeros(5)

# Modificamos el tercer elemento del array (índice 2) y le asignamos el valor 5.
array[2] = 5

# Mostramos el array por consola para verificar el cambio.
print(array)


[0. 0. 5. 0. 0.]


**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [9]:
#todo:
# np.random.rand(3, 3) genera una matriz de tamaño 3x3 con valores aleatorios entre 0 y 1
matriz = np.random.rand(3, 3)

# Imprimir la matriz generada en la consola
print(matriz)

[[0.60910188 0.98975625 0.50396191]
 [0.53249498 0.71835176 0.54383566]
 [0.79632092 0.04171727 0.77149231]]


**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [ ]:
#todo:
import random # Importamos la libreria random
# Crear el array inicial
arr = np.array([10, 20, 30, 40, 50])

# 1. Sumar 5 a cada elemento
arr_sumado = arr + 5

# 2. Generar un número aleatorio entre 1 y 10
numero_aleatorio = random.randint(1, 10)

# 3. Multiplicar cada elemento del array sumado por el número aleatorio generado
arr_multiplicado = arr_sumado * numero_aleatorio

# Imprimir el resultado
print("Array después de sumar 5:", arr_sumado)
print("Número aleatorio generado:", numero_aleatorio)
print("Array después de multiplicar por el número aleatorio:", arr_multiplicado)

TypeError: int() can't convert non-string with explicit base

**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [ ]:
#todo:

**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares yu luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [ ]:
#todo: 

